SQUARE_CAPABILITIES = (
    ("CREDIT_CARD_PROCESSING", "Credit Card Processing"),
    ("AUTOMATIC_TRANSFERS", "Automatic Transfers"),
)

STATUS_ACTIVE = "ACTIVE"
STATUS_INACTIVE = "INACTIVE"
SQUARE_STATUS = ((STATUS_ACTIVE, "Active"), (STATUS_INACTIVE, "Inactive"))
SQUARE_LOCATION_TYPE = (("PHYSICAL", "Physical"), ("MOBILE", "Mobile"))

DAY_SUNDAY = "SUN"
DAY_MONDAY = "MON"
DAY_TUESDAY = "TUE"
DAY_WEDNESDAY = "WED"
DAY_THURSDAY = "THU"
DAY_FRIDAY = "FRI"
DAY_SATURDAY = "SAT"
SQUARE_WEEKDAYS = (
    (DAY_SUNDAY, "Sunday"),
    (DAY_MONDAY, "Monday"),
    (DAY_TUESDAY, "Tuesday"),
    (DAY_WEDNESDAY, "Wednesday"),
    (DAY_THURSDAY, "Thursday"),
    (DAY_FRIDAY, "Friday"),
    (DAY_SATURDAY, "Saturday"),
)
