# Generated by Django 2.1.4 on 2018-12-16 16:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='NavbarLink',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.BooleanField(default=True)),
                ('order', models.IntegerField()),
                ('title', models.CharField(blank=True, max_length=128, null=True)),
                ('link', models.URLField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='NavbarMenu',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.BooleanField(default=True)),
                ('root_menu', models.BooleanField(default=False)),
                ('order', models.IntegerField()),
                ('name', models.CharField(blank=True, max_length=128, null=True)),
                ('menu_items', models.ManyToManyField(null=True, to='navbar.NavbarLink')),
            ],
        ),
        migrations.AddField(
            model_name='navbarlink',
            name='submenu',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='navbar.NavbarMenu'),
        ),
    ]
