# Generated by Django 2.1.4 on 2018-12-16 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('navbar', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='navbarmenu',
            name='menu_items',
            field=models.ManyToManyField(to='navbar.NavbarLink'),
        ),
    ]
