# Generated by Django 2.1.4 on 2018-12-16 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('navbar', '0002_auto_20181216_1655'),
    ]

    operations = [
        migrations.AlterField(
            model_name='navbarmenu',
            name='menu_items',
            field=models.ManyToManyField(blank=True, to='navbar.NavbarLink'),
        ),
    ]
