# Generated by Django 2.1.4 on 2018-12-16 19:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('navbar', '0003_auto_20181216_1912'),
    ]

    operations = [
        migrations.AlterField(
            model_name='navbarlink',
            name='submenu',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='navbar.NavbarMenu'),
        ),
    ]
