# Generated by Django 2.1.4 on 2018-12-16 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('navbar', '0004_auto_20181216_1915'),
    ]

    operations = [
        migrations.AddField(
            model_name='navbarlink',
            name='target',
            field=models.CharField(choices=[('_self', 'Normal'), ('_top', 'Break Frames'), ('_blank', 'New Tab/Window')], default='_self', max_length=16),
        ),
    ]
